
%% set color
parameters.frame_colors        = 255 .* hsv2rgb(   [   mod(linspace(0,1,parameters.frame_number+1)+rand(),1);...
                                                        ones(1,parameters.frame_number+1);...
                                                        ones(1,parameters.frame_number+1)...
                                                    ]');
parameters.frame_colors        = parameters.frame_colors(randperm(parameters.frame_number),:);
